/**
 * Condensed Ozon Seller API reference — 410 endpoints across 51 categories.
 * Generated from https://docs.ozon.ru/api/seller/swagger.json
 *
 * Used as MCP resources so AI agents know which Ozon API methods exist.
 */

export interface OzonEndpoint {
  method: string
  path: string
  summary: string
}

export interface OzonCategory {
  name: string
  endpoints: OzonEndpoint[]
}

export const OZON_API_CATEGORIES: OzonCategory[] = [
  { name: "APIkey", endpoints: [
    { method: "POST", path: "/v1/roles", summary: "Получить список ролей и методов по API-ключу" },
  ]},
  { name: "AnalyticsAPI", endpoints: [
    { method: "POST", path: "/v2/analytics/stock_on_warehouses", summary: "Отчёт по остаткам и товарам" },
    { method: "POST", path: "/v1/analytics/turnover/stocks", summary: "Оборачиваемость товара" },
    { method: "POST", path: "/v1/analytics/average-delivery-time", summary: "Получить аналитику по среднему времени доставки" },
    { method: "POST", path: "/v1/analytics/average-delivery-time/details", summary: "Получить детальную аналитику по среднему времени доставки" },
    { method: "POST", path: "/v1/analytics/average-delivery-time/summary", summary: "Получить общую аналитику по среднему времени доставки" },
  ]},
  { name: "BarcodeAPI", endpoints: [
    { method: "POST", path: "/v1/barcode/add", summary: "Привязать штрихкод к товару" },
    { method: "POST", path: "/v1/barcode/generate", summary: "Создать штрихкод для товара" },
  ]},
  { name: "BetaMethod", endpoints: [
    { method: "POST", path: "/v1/analytics/manage/stocks", summary: "Управление остатками" },
    { method: "POST", path: "/v1/analytics/stocks", summary: "Получить аналитику по остаткам" },
    { method: "POST", path: "/v1/removal/from-supply/list", summary: "Отчёт по вывозу и утилизации с поставки FBO" },
    { method: "POST", path: "/v1/removal/from-stock/list", summary: "Отчёт по вывозу и утилизации со стока FBO" },
    { method: "POST", path: "/v1/product/stairway-discount/by-quantity/set", summary: "Управлять скидкой от количества" },
    { method: "POST", path: "/v1/product/stairway-discount/by-quantity/get", summary: "Получить информацию о скидке от количества" },
    { method: "POST", path: "/v1/finance/balance", summary: "Получить отчёт о балансе" },
    { method: "POST", path: "/v1/product/prices/details", summary: "Получить подробную информацию о ценах товаров" },
    { method: "POST", path: "/v1/cargoes/get", summary: "Получить информацию о грузоместах" },
    { method: "POST", path: "/v2/actions/discounts-task/list", summary: "Получить список заявок на скидку" },
    { method: "POST", path: "/v1/returns/settings/utilization/history", summary: "Получить историю изменений автоутилизации" },
    { method: "POST", path: "/v1/returns/settings/utilization/info", summary: "Получить настройки автоутилизации" },
    { method: "POST", path: "/v1/returns/settings/utilization/update", summary: "Обновить настройки автоутилизации" },
    { method: "POST", path: "/v1/carriage/act-discrepancy/pdf", summary: "Получить акт о расхождениях по отгрузке FBS" },
  ]},
  { name: "BrandAPI", endpoints: [
    { method: "POST", path: "/v1/brand/company-certification/list", summary: "Список сертифицируемых брендов" },
  ]},
  { name: "CancelReasonAPI", endpoints: [
    { method: "POST", path: "/v1/cancel-reason/list", summary: "Причины отмены отправлений" },
    { method: "POST", path: "/v1/cancel-reason/list-by-order", summary: "Причины отмены заказа" },
    { method: "POST", path: "/v1/cancel-reason/list-by-posting", summary: "Причины отмены отправления" },
  ]},
  { name: "CancellationAPI", endpoints: [
    { method: "POST", path: "/v2/conditional-cancellation/list", summary: "Получить список заявок на отмену rFBS" },
    { method: "POST", path: "/v2/conditional-cancellation/approve", summary: "Подтвердить заявку на отмену rFBS" },
    { method: "POST", path: "/v2/conditional-cancellation/reject", summary: "Отклонить заявку на отмену rFBS" },
  ]},
  { name: "CategoryAPI", endpoints: [
    { method: "POST", path: "/v1/description-category/tree", summary: "Дерево категорий и типов товаров" },
    { method: "POST", path: "/v1/description-category/attribute", summary: "Список характеристик категории" },
    { method: "POST", path: "/v1/description-category/attribute/values", summary: "Справочник значений характеристики" },
    { method: "POST", path: "/v1/description-category/attribute/values/search", summary: "Поиск по справочным значениям характеристики" },
  ]},
  { name: "CertificationAPI", endpoints: [
    { method: "GET", path: "/v1/product/certificate/accordance-types", summary: "Список типов соответствия требованиям (v1)" },
    { method: "GET", path: "/v2/product/certificate/accordance-types/list", summary: "Список типов соответствия требованиям (v2)" },
    { method: "GET", path: "/v1/product/certificate/types", summary: "Справочник типов документов" },
    { method: "POST", path: "/v2/product/certification/list", summary: "Список сертифицируемых категорий" },
    { method: "POST", path: "/v1/product/certificate/create", summary: "Добавить сертификаты для товаров" },
    { method: "POST", path: "/v1/product/certificate/bind", summary: "Привязать сертификат к товару" },
    { method: "POST", path: "/v1/product/certificate/delete", summary: "Удалить сертификат" },
    { method: "POST", path: "/v1/product/certificate/info", summary: "Информация о сертификате" },
    { method: "POST", path: "/v1/product/certificate/list", summary: "Список сертификатов" },
    { method: "POST", path: "/v1/product/certificate/product_status/list", summary: "Список возможных статусов товаров" },
    { method: "POST", path: "/v1/product/certificate/products/list", summary: "Список товаров, привязанных к сертификату" },
    { method: "POST", path: "/v1/product/certificate/unbind", summary: "Отвязать товар от сертификата" },
    { method: "POST", path: "/v1/product/certificate/rejection_reasons/list", summary: "Возможные причины отклонения сертификата" },
    { method: "POST", path: "/v1/product/certificate/status/list", summary: "Возможные статусы сертификатов" },
  ]},
  { name: "ChatAPI", endpoints: [
    { method: "POST", path: "/v1/chat/send/file", summary: "Отправить файл" },
    { method: "POST", path: "/v2/chat/list", summary: "Список чатов" },
    { method: "POST", path: "/v3/chat/list", summary: "Список чатов (v3)" },
    { method: "POST", path: "/v3/chat/history", summary: "История чата" },
  ]},
  { name: "DeliveryAPI", endpoints: [
    { method: "POST", path: "/v1/delivery/check", summary: "Проверить доступность доставки для покупателя" },
    { method: "POST", path: "/v2/delivery/checkout", summary: "Получить доступные варианты доставки" },
    { method: "POST", path: "/v1/delivery/map", summary: "Отрисовать точки на карте" },
    { method: "POST", path: "/v1/delivery/point/info", summary: "Получить информацию о точке самовывоза" },
    { method: "POST", path: "/v1/delivery/point/list", summary: "Получить список точек самовывоза" },
  ]},
  { name: "DeliveryFBP", endpoints: [
    { method: "POST", path: "/v1/fbp/act-from/create", summary: "Сгенерировать акт приёмки" },
    { method: "POST", path: "/v1/fbp/act-from/get", summary: "Получить статус генерации акта приёмки" },
    { method: "POST", path: "/v1/fbp/act-to/create", summary: "Сгенерировать транспортную накладную" },
    { method: "POST", path: "/v1/fbp/act-to/get", summary: "Получить статус генерации транспортной накладной" },
    { method: "POST", path: "/v1/fbp/archive/get", summary: "Получить информацию о завершённой поставке" },
    { method: "POST", path: "/v1/fbp/archive/list", summary: "Получить список завершённых поставок" },
    { method: "POST", path: "/v1/fbp/label/create", summary: "Cоздать задание на генерацию этикеток" },
    { method: "POST", path: "/v1/fbp/label/get", summary: "Получить статус задания на генерацию этикеток" },
    { method: "POST", path: "/v1/fbp/order/get", summary: "Получить информацию о конкретной поставке" },
    { method: "POST", path: "/v1/fbp/order/list", summary: "Получить список поставок" },
  ]},
  { name: "DeliveryFBPDraft", endpoints: [
    { method: "POST", path: "/v1/fbp/warehouse/list", summary: "Получить список партнёрских складов" },
    { method: "POST", path: "/v1/fbp/draft/get", summary: "Получить информацию о черновике поставки" },
    { method: "POST", path: "/v1/fbp/draft/list", summary: "Список черновиков поставки" },
  ]},
  { name: "DeliveryFBS", endpoints: [
    { method: "POST", path: "/v1/carriage/create", summary: "Создание отгрузки" },
    { method: "POST", path: "/v1/carriage/approve", summary: "Подтверждение отгрузки" },
    { method: "POST", path: "/v1/carriage/set-postings", summary: "Изменение состава отгрузки" },
    { method: "POST", path: "/v1/carriage/cancel", summary: "Удаление отгрузки" },
    { method: "POST", path: "/v1/carriage/delivery/list", summary: "Список методов доставки и отгрузок" },
    { method: "POST", path: "/v2/carriage/delivery/list", summary: "Список методов доставки и отгрузок (v2)" },
    { method: "POST", path: "/v2/posting/fbs/act/create", summary: "Подтвердить отгрузку и создать документы" },
    { method: "POST", path: "/v1/posting/carriage-available/list", summary: "Список доступных перевозок" },
    { method: "POST", path: "/v1/carriage/get", summary: "Информация о перевозке" },
    { method: "POST", path: "/v1/posting/fbs/split", summary: "Разделить заказ на отправления без сборки" },
    { method: "POST", path: "/v2/posting/fbs/act/get-postings", summary: "Список отправлений в акте" },
    { method: "POST", path: "/v2/posting/fbs/act/get-container-labels", summary: "Этикетки для грузового места" },
    { method: "POST", path: "/v2/posting/fbs/act/get-barcode", summary: "Штрихкод для отгрузки отправления" },
    { method: "POST", path: "/v2/posting/fbs/act/get-barcode/text", summary: "Значение штрихкода для отгрузки отправления" },
    { method: "POST", path: "/v2/posting/fbs/digital/act/check-status", summary: "Статус формирования накладной" },
    { method: "POST", path: "/v2/posting/fbs/act/get-pdf", summary: "Получить PDF c документами" },
    { method: "POST", path: "/v2/posting/fbs/act/list", summary: "Список актов по отгрузкам" },
    { method: "POST", path: "/v2/posting/fbs/digital/act/get-pdf", summary: "Получить лист отгрузки по перевозке" },
    { method: "POST", path: "/v2/posting/fbs/act/check-status", summary: "Статус отгрузки и документов" },
    { method: "POST", path: "/v1/posting/fbs/traceable/split", summary: "Разделить отправление с прослеживаемыми товарами" },
    { method: "POST", path: "/v1/posting/fbs/product/traceable/attribute", summary: "Получить список незаполненных атрибутов для прослеживаемых товаров" },
    { method: "POST", path: "/v1/carriage/ettn/status", summary: "Получить статус проверки электронной ТТН на прослеживаемой перевозке FBS" },
    { method: "POST", path: "/v1/assembly/carriage/posting/list", summary: "Получить список отправлений в отгрузке" },
    { method: "POST", path: "/v1/assembly/carriage/product/list", summary: "Получить список товаров в отгрузке" },
    { method: "POST", path: "/v1/assembly/fbs/posting/list", summary: "Получить список отправлений" },
    { method: "POST", path: "/v1/assembly/fbs/product/list", summary: "Получить список товаров в отправлениях" },
  ]},
  { name: "DeliveryrFBS", endpoints: [
    { method: "POST", path: "/v2/fbs/posting/tracking-number/set", summary: "Добавить трек-номера" },
    { method: "POST", path: "/v2/fbs/posting/delivering", summary: "Изменить статус на «Доставляется»" },
    { method: "POST", path: "/v2/fbs/posting/last-mile", summary: "Изменить статус на «Последняя миля»" },
    { method: "POST", path: "/v2/fbs/posting/delivered", summary: "Изменить статус на «Доставлено»" },
    { method: "POST", path: "/v1/posting/fbs/timeslot/change-restrictions", summary: "Доступные даты для переноса доставки" },
    { method: "POST", path: "/v1/posting/fbs/timeslot/set", summary: "Перенести дату доставки" },
    { method: "POST", path: "/v1/posting/cutoff/set", summary: "Уточнить дату отгрузки отправления" },
  ]},
  { name: "Digital", endpoints: [
    { method: "POST", path: "/v1/posting/digital/codes/upload", summary: "Загрузить коды цифровых товаров для отправления" },
    { method: "POST", path: "/v1/posting/digital/list", summary: "Получить список отправлений" },
    { method: "POST", path: "/v1/product/digital/stocks/import", summary: "Обновить количество цифровых товаров" },
  ]},
  { name: "DraftDirectFBP", endpoints: [
    { method: "POST", path: "/v1/fbp/draft/direct/seller-dlv/create", summary: "Создать черновик с доставкой силами продавца" },
    { method: "POST", path: "/v1/fbp/draft/direct/seller-dlv/edit", summary: "Обновить информацию о доставке силами продавца в черновике" },
    { method: "POST", path: "/v1/fbp/draft/direct/timeslot/edit", summary: "Отредактировать таймслот в черновике" },
    { method: "POST", path: "/v1/fbp/draft/direct/timeslot/get", summary: "Получить список таймслотов для прямой поставки" },
    { method: "POST", path: "/v1/fbp/draft/direct/create", summary: "Создать черновик заявки на поставку" },
    { method: "POST", path: "/v1/fbp/draft/direct/delete", summary: "Удалить черновик заявки на поставку" },
    { method: "POST", path: "/v1/fbp/draft/direct/product/validate", summary: "Проверить список товаров для склада партнёра" },
    { method: "POST", path: "/v1/fbp/draft/direct/registrate", summary: "Перевести черновик в действующую поставку" },
    { method: "POST", path: "/v1/fbp/draft/direct/tpl-dlv/create", summary: "Создать черновик заявки на доставку сторонней ТК" },
    { method: "POST", path: "/v1/fbp/draft/direct/tpl-dlv/edit", summary: "Редактировать черновик поставки со способом доставки сторонней ТК" },
  ]},
  { name: "DraftDropOffFBP", endpoints: [
    { method: "POST", path: "/v1/fbp/draft/drop-off/create", summary: "Создать черновик для доставки в drop-off пункт" },
    { method: "POST", path: "/v1/fbp/draft/drop-off/delete", summary: "Удалить черновик для доставки в drop-off пункт" },
    { method: "POST", path: "/v1/fbp/draft/drop-off/dlv/edit", summary: "Отредактировать детали доставки для drop-off черновика" },
    { method: "POST", path: "/v1/fbp/draft/drop-off/registrate", summary: "Перевести черновик в действующую поставку" },
    { method: "POST", path: "/v1/fbp/draft/drop-off/province/list", summary: "Получить список провинций" },
    { method: "POST", path: "/v1/fbp/draft/drop-off/point/list", summary: "Получить список drop-off пунктов в провинции" },
    { method: "POST", path: "/v1/fbp/draft/drop-off/point/timetable", summary: "Получить расписание работы drop-off пункта" },
    { method: "POST", path: "/v1/fbp/draft/drop-off/product/validate", summary: "Проверить список товаров для склада партнёра" },
  ]},
  { name: "DraftPickupFBP", endpoints: [
    { method: "POST", path: "/v1/fbp/draft/pick-up/create", summary: "Создать черновик заявки на pick-up поставку" },
    { method: "POST", path: "/v1/fbp/draft/pick-up/delete", summary: "Отменить черновик заявки на pick-up поставку" },
    { method: "POST", path: "/v1/fbp/draft/pick-up/dlv/edit", summary: "Изменить черновик заявки на pick-up поставку" },
    { method: "POST", path: "/v1/fbp/draft/pick-up/product/validate", summary: "Провалидировать список товаров для pick-up поставки" },
    { method: "POST", path: "/v1/fbp/draft/pick-up/registrate", summary: "Перевести черновик в действующую поставку" },
  ]},
  { name: "FBO", endpoints: [
    { method: "POST", path: "/v2/posting/fbo/list", summary: "Список отправлений" },
    { method: "POST", path: "/v2/posting/fbo/get", summary: "Информация об отправлении" },
    { method: "POST", path: "/v1/posting/fbo/cancel-reason/list", summary: "Причины отмены отправлений по схеме FBO" },
    { method: "POST", path: "/v1/supply-order/status/counter", summary: "Количество заявок по статусам" },
    { method: "POST", path: "/v1/supply-order/bundle", summary: "Состав поставки или заявки на поставку" },
    { method: "POST", path: "/v3/supply-order/list", summary: "Список заявок на поставку на склад Ozon" },
    { method: "POST", path: "/v3/supply-order/get", summary: "Информация о заявке на поставку" },
    { method: "POST", path: "/v1/supply-order/timeslot/get", summary: "Интервалы поставки" },
    { method: "POST", path: "/v1/supply-order/timeslot/update", summary: "Обновить интервал поставки" },
    { method: "POST", path: "/v1/supply-order/timeslot/status", summary: "Статус интервала поставки" },
    { method: "POST", path: "/v1/supply-order/pass/create", summary: "Указать данные о водителе и автомобиле" },
    { method: "POST", path: "/v1/supply-order/pass/status", summary: "Статус ввода данных о водителе и автомобиле" },
    { method: "POST", path: "/v1/supply-order/details", summary: "Получить подробную информацию о заявке на поставку" },
    { method: "GET", path: "/v1/supplier/available_warehouses", summary: "Загруженность складов Ozon" },
  ]},
  { name: "FBS", endpoints: [
    { method: "POST", path: "/v3/posting/fbs/unfulfilled/list", summary: "Список необработанных отправлений" },
    { method: "POST", path: "/v3/posting/fbs/list", summary: "Список отправлений" },
    { method: "POST", path: "/v3/posting/fbs/get", summary: "Получить информацию об отправлении по идентификатору" },
    { method: "POST", path: "/v2/posting/fbs/get-by-barcode", summary: "Получить информацию об отправлении по штрихкоду" },
    { method: "POST", path: "/v3/posting/multiboxqty/set", summary: "Указать количество коробок для многокоробочных отправлений" },
    { method: "POST", path: "/v2/posting/fbs/product/country/list", summary: "Список доступных стран-изготовителей" },
    { method: "POST", path: "/v2/posting/fbs/product/country/set", summary: "Добавить информацию о стране-изготовителе товара" },
    { method: "POST", path: "/v1/posting/fbs/restrictions", summary: "Получить ограничения пункта приёма" },
    { method: "POST", path: "/v2/posting/fbs/package-label", summary: "Напечатать этикетку" },
    { method: "POST", path: "/v1/posting/fbs/package-label/create", summary: "Создать задание на выгрузку этикеток" },
    { method: "POST", path: "/v2/posting/fbs/package-label/create", summary: "Создать задание на формирование этикеток" },
    { method: "POST", path: "/v1/posting/fbs/package-label/get", summary: "Получить файл с этикетками" },
    { method: "POST", path: "/v1/posting/fbs/cancel-reason", summary: "Причины отмены отправления" },
    { method: "POST", path: "/v2/posting/fbs/cancel-reason/list", summary: "Причины отмены отправлений" },
    { method: "POST", path: "/v2/posting/fbs/product/cancel", summary: "Отменить отправку некоторых товаров в отправлении" },
    { method: "POST", path: "/v2/posting/fbs/cancel", summary: "Отменить отправление" },
    { method: "POST", path: "/v2/posting/fbs/arbitration", summary: "Открыть спор по отправлению" },
    { method: "POST", path: "/v2/posting/fbs/awaiting-delivery", summary: "Передать отправление к отгрузке" },
    { method: "POST", path: "/v1/posting/fbs/pick-up-code/verify", summary: "Проверить код курьера" },
    { method: "POST", path: "/v1/posting/global/etgb", summary: "Таможенные декларации ETGB" },
    { method: "POST", path: "/v1/posting/unpaid-legal/product/list", summary: "Список неоплаченных товаров юрлиц" },
  ]},
  { name: "FBS_rFBS_Marks", endpoints: [
    { method: "POST", path: "/v4/posting/fbs/ship", summary: "Собрать заказ (v4)" },
    { method: "POST", path: "/v4/posting/fbs/ship/package", summary: "Частичная сборка отправления (v4)" },
    { method: "POST", path: "/v6/fbs/posting/product/exemplar/set", summary: "Проверить и сохранить данные экземпляров" },
    { method: "POST", path: "/v6/fbs/posting/product/exemplar/create-or-get", summary: "Получить данные созданных экземпляров" },
    { method: "POST", path: "/v5/fbs/posting/product/exemplar/status", summary: "Получить статус добавления экземпляров" },
    { method: "POST", path: "/v5/fbs/posting/product/exemplar/validate", summary: "Валидация кодов маркировки" },
    { method: "POST", path: "/v1/fbs/posting/product/exemplar/update", summary: "Обновить данные экземпляров" },
  ]},
  { name: "FBSWarehouseSetup", endpoints: [
    { method: "POST", path: "/v1/warehouse/fbs/create/drop-off/list", summary: "Список drop-off пунктов для создания склада" },
    { method: "POST", path: "/v1/warehouse/fbs/update/drop-off/list", summary: "Список drop-off пунктов для изменения склада" },
    { method: "POST", path: "/v1/warehouse/fbs/create/drop-off/timeslot/list", summary: "Таймслоты для создания склада с отгрузкой drop-off" },
    { method: "POST", path: "/v1/warehouse/fbs/update/drop-off/timeslot/list", summary: "Таймслоты для обновления склада с отгрузкой drop-off" },
    { method: "POST", path: "/v1/warehouse/fbs/create/pick-up/timeslot/list", summary: "Таймслоты для создания склада с отгрузкой pick-up" },
    { method: "POST", path: "/v1/warehouse/fbs/update/pick-up/timeslot/list", summary: "Таймслоты для обновления склада с отгрузкой pick-up" },
    { method: "POST", path: "/v1/warehouse/fbs/create", summary: "Создать склад" },
    { method: "POST", path: "/v1/warehouse/fbs/update", summary: "Обновить склад" },
    { method: "POST", path: "/v1/warehouse/fbs/first-mile/update", summary: "Обновить первую милю" },
    { method: "POST", path: "/v1/warehouse/fbs/create/return-point/list", summary: "Список пунктов возврата для создания склада" },
    { method: "POST", path: "/v1/warehouse/fbs/update/return-point/list", summary: "Список пунктов возврата для обновления склада" },
    { method: "POST", path: "/v1/warehouse/fbs/return-mile/info", summary: "Информация о возвратной миле" },
    { method: "POST", path: "/v1/warehouse/fbs/return-mile/check", summary: "Проверить необходимость возвратной мили" },
    { method: "POST", path: "/v1/warehouse/fbs/pickup/courier/create", summary: "Создать вызов курьера на забор pick-up" },
    { method: "POST", path: "/v1/warehouse/fbs/pickup/courier/cancel", summary: "Отменить вызов курьера на забор pick-up" },
    { method: "POST", path: "/v1/warehouse/fbs/pickup/history/list", summary: "История отгрузок курьерам" },
    { method: "POST", path: "/v1/warehouse/fbs/pickup/planning/list", summary: "Список складов для планирования отгрузок курьеру" },
  ]},
  { name: "FboPostingAPI", endpoints: [
    { method: "POST", path: "/v1/posting/cancel", summary: "Отменить отправление из заказа" },
    { method: "POST", path: "/v1/posting/cancel/status", summary: "Проверить статус отмены отправления" },
    { method: "POST", path: "/v1/posting/marks", summary: "Получить маркировки экземпляров из отправления" },
  ]},
  { name: "FboSupplyRequest", endpoints: [
    { method: "POST", path: "/v1/cluster/list", summary: "Информация о кластерах и их складах" },
    { method: "POST", path: "/v1/warehouse/fbo/list", summary: "Поиск точек для отгрузки поставки" },
    { method: "POST", path: "/v1/draft/create", summary: "Создать черновик заявки на поставку" },
    { method: "POST", path: "/v1/draft/crossdock/create", summary: "Создать черновик заявки на поставку кросс-докингом" },
    { method: "POST", path: "/v1/draft/direct/create", summary: "Создать черновик заявки на прямую поставку" },
    { method: "POST", path: "/v1/draft/multi-cluster/create", summary: "Создать черновик для нескольких кластеров" },
    { method: "POST", path: "/v1/draft/create/info", summary: "Информация о черновике заявки на поставку" },
    { method: "POST", path: "/v1/draft/timeslot/info", summary: "Доступные таймслоты" },
    { method: "POST", path: "/v2/draft/create/info", summary: "Информация о черновике заявки на поставку (v2)" },
    { method: "POST", path: "/v1/draft/supply/create", summary: "Создать заявку на поставку по черновику" },
    { method: "POST", path: "/v1/draft/supply/create/status", summary: "Информация о создании заявки на поставку" },
    { method: "POST", path: "/v2/draft/timeslot/info", summary: "Список доступных таймслотов (v2)" },
    { method: "POST", path: "/v1/cargoes/create", summary: "Установка грузомест" },
    { method: "POST", path: "/v1/cargoes/create/info", summary: "Информация по установке грузомест" },
    { method: "POST", path: "/v2/cargoes/create/info", summary: "Информация по установке грузомест (v2)" },
    { method: "POST", path: "/v1/cargoes/delete", summary: "Удалить грузоместо в заявке на поставку" },
    { method: "POST", path: "/v1/cargoes/delete/status", summary: "Статус удаления грузоместа" },
    { method: "POST", path: "/v1/cargoes/rules/get", summary: "Чек-лист по установке грузомест FBO" },
    { method: "POST", path: "/v1/cargoes-label/create", summary: "Сгенерировать этикетки для грузомест" },
    { method: "POST", path: "/v1/cargoes-label/get", summary: "Получить идентификатор этикетки для грузомест" },
    { method: "GET", path: "/v1/cargoes-label/file/{file_guid}", summary: "Получить PDF с этикетками грузовых мест" },
    { method: "POST", path: "/v1/supply-order/cancel", summary: "Отменить заявку на поставку" },
    { method: "POST", path: "/v1/supply-order/cancel/status", summary: "Статус отмены заявки на поставку" },
    { method: "POST", path: "/v1/supply-order/content/update", summary: "Редактирование товарного состава" },
    { method: "POST", path: "/v1/supply-order/content/update/status", summary: "Статус редактирования товарного состава" },
    { method: "POST", path: "/v1/supply-order/content/update/validation", summary: "Проверить новый товарный состав" },
    { method: "POST", path: "/v2/draft/supply/create", summary: "Создать заявку по черновику (v2)" },
    { method: "POST", path: "/v2/draft/supply/create/status", summary: "Статус создания заявки (v2)" },
    { method: "POST", path: "/v1/warehouse/fbo/seller/list", summary: "Список складов продавца" },
  ]},
  { name: "FinanceAPI", endpoints: [
    { method: "POST", path: "/v2/finance/realization", summary: "Отчёт о реализации товаров (v2)" },
    { method: "POST", path: "/v1/finance/realization/posting", summary: "Позаказный отчёт о реализации товаров" },
    { method: "POST", path: "/v3/finance/transaction/list", summary: "Список транзакций" },
    { method: "POST", path: "/v3/finance/transaction/totals", summary: "Суммы транзакций" },
    { method: "POST", path: "/v1/finance/document-b2b-sales", summary: "Реестр продаж юридическим лицам" },
    { method: "POST", path: "/v1/finance/document-b2b-sales/json", summary: "Реестр продаж юрлицам в JSON-формате" },
    { method: "POST", path: "/v1/finance/mutual-settlement", summary: "Отчёт о взаиморасчётах" },
    { method: "POST", path: "/v1/finance/products/buyout", summary: "Отчёт о выкупленных товарах" },
    { method: "POST", path: "/v1/finance/compensation", summary: "Отчёт о компенсациях" },
    { method: "POST", path: "/v1/finance/decompensation", summary: "Отчёт о декомпенсациях" },
  ]},
  { name: "OrderAPI", endpoints: [
    { method: "POST", path: "/v1/order/cancel", summary: "Отменить заказ" },
    { method: "POST", path: "/v1/order/cancel/check", summary: "Проверить возможность отмены заказа" },
    { method: "POST", path: "/v1/order/cancel/status", summary: "Статус отмены заказа" },
    { method: "POST", path: "/v2/order/create", summary: "Создать заказ" },
  ]},
  { name: "OrderDirectFBP", endpoints: [
    { method: "POST", path: "/v1/fbp/order/direct/cancel", summary: "Отменить поставку" },
    { method: "POST", path: "/v1/fbp/order/direct/seller-dlv/edit", summary: "Обновить информацию о доставке силами продавца" },
    { method: "POST", path: "/v1/fbp/order/direct/timeslot/edit", summary: "Отредактировать таймслот в заявке на поставку" },
    { method: "POST", path: "/v1/fbp/order/direct/timeslot/list", summary: "Список таймслотов для поставки" },
  ]},
  { name: "OrderDropOffFBP", endpoints: [
    { method: "POST", path: "/v1/fbp/order/drop-off/cancel", summary: "Отменить поставку drop-off" },
    { method: "POST", path: "/v1/fbp/order/drop-off/dlv/edit", summary: "Отредактировать информацию о поставке на drop-off" },
    { method: "POST", path: "/v1/fbp/order/drop-off/timetable", summary: "Получить график работы drop-off пункта" },
  ]},
  { name: "OrderPickupFBP", endpoints: [
    { method: "POST", path: "/v1/fbp/order/pick-up/cancel", summary: "Отменить pick-up поставку" },
    { method: "POST", path: "/v1/fbp/order/pick-up/dlv/edit", summary: "Изменить данные о точке забора" },
  ]},
  { name: "Pass", endpoints: [
    { method: "POST", path: "/v1/pass/list", summary: "Список пропусков" },
    { method: "POST", path: "/v1/carriage/pass/create", summary: "Создать пропуск" },
    { method: "POST", path: "/v1/carriage/pass/update", summary: "Обновить пропуск" },
    { method: "POST", path: "/v1/carriage/pass/delete", summary: "Удалить пропуск" },
    { method: "POST", path: "/v1/return/pass/create", summary: "Создать пропуск для возврата" },
    { method: "POST", path: "/v1/return/pass/update", summary: "Обновить пропуск для возврата" },
    { method: "POST", path: "/v1/return/pass/delete", summary: "Удалить пропуск для возврата" },
  ]},
  { name: "PolygonAPI", endpoints: [
    { method: "POST", path: "/v1/polygon/create", summary: "Создать полигон доставки" },
    { method: "POST", path: "/v1/polygon/bind", summary: "Связать метод доставки с полигоном" },
    { method: "POST", path: "/v2/polygon/bind", summary: "Связать метод доставки с полигоном (v2)" },
    { method: "POST", path: "/v1/polygon/delete", summary: "Удалить полигон из области доставки" },
    { method: "POST", path: "/v1/polygon/list", summary: "Список установленных полигонов на метод доставки" },
    { method: "POST", path: "/v1/polygon/time/coordinates/update", summary: "Обновить координаты полигона доставки" },
    { method: "POST", path: "/v1/polygon/time/set", summary: "Установить время доставки в полигоне" },
  ]},
  { name: "Premium", endpoints: [
    { method: "POST", path: "/v1/chat/send/message", summary: "Отправить сообщение" },
    { method: "POST", path: "/v1/chat/start", summary: "Создать новый чат" },
    { method: "POST", path: "/v2/chat/read", summary: "Отметить сообщения как прочитанные" },
    { method: "POST", path: "/v1/analytics/data", summary: "Данные аналитики" },
    { method: "POST", path: "/v1/analytics/product-queries", summary: "Информация о запросах моих товаров" },
    { method: "POST", path: "/v1/analytics/product-queries/details", summary: "Детализация запросов по товару" },
    { method: "POST", path: "/v1/finance/realization/by-day", summary: "Отчёт о реализации товаров за день" },
    { method: "POST", path: "/v1/search-queries/text", summary: "Список поисковых запросов по тексту" },
    { method: "POST", path: "/v1/search-queries/top", summary: "Список популярных поисковых запросов" },
  ]},
  { name: "Prices_Stocks_API", endpoints: [
    { method: "POST", path: "/v2/products/stocks", summary: "Обновить количество товаров на складах" },
    { method: "POST", path: "/v4/product/info/stocks", summary: "Информация о количестве товаров" },
    { method: "POST", path: "/v1/product/info/warehouse/stocks", summary: "Остатки на складе FBS и rFBS" },
    { method: "POST", path: "/v1/product/info/stocks-by-warehouse/fbs", summary: "Остатки на складах продавца (FBS и rFBS)" },
    { method: "POST", path: "/v2/product/info/stocks-by-warehouse/fbs", summary: "Остатки на складах продавца (v2)" },
    { method: "POST", path: "/v1/product/import/prices", summary: "Обновить цену" },
    { method: "POST", path: "/v1/product/action/timer/update", summary: "Обновление таймера актуальности минимальной цены" },
    { method: "POST", path: "/v1/product/action/timer/status", summary: "Статус установленного таймера" },
    { method: "POST", path: "/v5/product/info/prices", summary: "Информация о цене товара" },
    { method: "POST", path: "/v1/product/info/discounted", summary: "Информация об уценке по SKU уценённого товара" },
    { method: "POST", path: "/v1/product/update/discount", summary: "Установить скидку на уценённый товар" },
  ]},
  { name: "PricingStrategyAPI", endpoints: [
    { method: "POST", path: "/v1/pricing-strategy/competitors/list", summary: "Список конкурентов" },
    { method: "POST", path: "/v1/pricing-strategy/list", summary: "Список стратегий" },
    { method: "POST", path: "/v1/pricing-strategy/create", summary: "Создать стратегию" },
    { method: "POST", path: "/v1/pricing-strategy/info", summary: "Информация о стратегии" },
    { method: "POST", path: "/v1/pricing-strategy/update", summary: "Обновить стратегию" },
    { method: "POST", path: "/v1/pricing-strategy/products/add", summary: "Добавить товары в стратегию" },
    { method: "POST", path: "/v1/pricing-strategy/strategy-ids-by-product-ids", summary: "ID стратегий по ID товаров" },
    { method: "POST", path: "/v1/pricing-strategy/products/list", summary: "Список товаров в стратегии" },
    { method: "POST", path: "/v1/pricing-strategy/product/info", summary: "Цена товара у конкурента" },
    { method: "POST", path: "/v1/pricing-strategy/products/delete", summary: "Удалить товары из стратегии" },
    { method: "POST", path: "/v1/pricing-strategy/status", summary: "Изменить статус стратегии" },
    { method: "POST", path: "/v1/pricing-strategy/delete", summary: "Удалить стратегию" },
  ]},
  { name: "ProductAPI", endpoints: [
    { method: "POST", path: "/v3/product/import", summary: "Создать или обновить товар" },
    { method: "POST", path: "/v1/product/import/info", summary: "Статус добавления или обновления товара" },
    { method: "POST", path: "/v1/product/import-by-sku", summary: "Создать товар по SKU" },
    { method: "POST", path: "/v1/product/attributes/update", summary: "Обновить характеристики товара" },
    { method: "POST", path: "/v1/product/pictures/import", summary: "Загрузить или обновить изображения товара" },
    { method: "POST", path: "/v3/product/list", summary: "Список товаров" },
    { method: "POST", path: "/v1/product/rating-by-sku", summary: "Контент-рейтинг товаров по SKU" },
    { method: "POST", path: "/v3/product/info/list", summary: "Информация о товарах по идентификаторам" },
    { method: "POST", path: "/v4/product/info/attributes", summary: "Описание характеристик товара" },
    { method: "POST", path: "/v1/product/info/description", summary: "Описание товара" },
    { method: "POST", path: "/v4/product/info/limit", summary: "Лимиты на ассортимент" },
    { method: "POST", path: "/v1/product/update/offer-id", summary: "Изменить артикулы товаров" },
    { method: "POST", path: "/v1/product/archive", summary: "Перенести товар в архив" },
    { method: "POST", path: "/v1/product/unarchive", summary: "Вернуть товар из архива" },
    { method: "POST", path: "/v2/products/delete", summary: "Удалить товар без SKU из архива" },
    { method: "POST", path: "/v1/product/info/subscription", summary: "Количество подписавшихся на товар" },
    { method: "POST", path: "/v1/product/related-sku/get", summary: "Получить связанные SKU" },
    { method: "POST", path: "/v2/product/pictures/info", summary: "Изображения товаров" },
    { method: "POST", path: "/v1/product/info/wrong-volume", summary: "Список товаров с некорректными ОВХ" },
    { method: "POST", path: "/v1/product/placement-zone/info", summary: "Зоны размещения товаров по SKU перед поставкой" },
  ]},
  { name: "Promos", endpoints: [
    { method: "GET", path: "/v1/actions", summary: "Список акций" },
    { method: "POST", path: "/v1/actions/candidates", summary: "Список доступных для акции товаров" },
    { method: "POST", path: "/v1/actions/products", summary: "Список участвующих в акции товаров" },
    { method: "POST", path: "/v1/actions/products/activate", summary: "Добавить товар в акцию" },
    { method: "POST", path: "/v1/actions/products/deactivate", summary: "Удалить товары из акции" },
    { method: "POST", path: "/v1/actions/discounts-task/list", summary: "Список заявок на скидку" },
    { method: "POST", path: "/v1/actions/discounts-task/approve", summary: "Согласовать заявку на скидку" },
    { method: "POST", path: "/v1/actions/discounts-task/decline", summary: "Отклонить заявку на скидку" },
  ]},
  { name: "Quants", endpoints: [
    { method: "POST", path: "/v1/product/quant/list", summary: "Список эконом-товаров" },
    { method: "POST", path: "/v1/product/quant/info", summary: "Информация об эконом-товаре" },
  ]},
  { name: "Questions_Answers", endpoints: [
    { method: "POST", path: "/v1/question/answer/create", summary: "Создать ответ на вопрос" },
    { method: "POST", path: "/v1/question/answer/delete", summary: "Удалить ответ на вопрос" },
    { method: "POST", path: "/v1/question/answer/list", summary: "Список ответов на вопрос" },
    { method: "POST", path: "/v1/question/change-status", summary: "Изменить статус вопросов" },
    { method: "POST", path: "/v1/question/count", summary: "Количество вопросов по статусам" },
    { method: "POST", path: "/v1/question/info", summary: "Информация о вопросе" },
    { method: "POST", path: "/v1/question/list", summary: "Список вопросов" },
    { method: "POST", path: "/v1/question/top-sku", summary: "Товары с наибольшим количеством вопросов" },
  ]},
  { name: "RFBSReturnsAPI", endpoints: [
    { method: "POST", path: "/v2/returns/rfbs/list", summary: "Список заявок на возврат" },
    { method: "POST", path: "/v2/returns/rfbs/get", summary: "Информация о заявке на возврат" },
    { method: "POST", path: "/v2/returns/rfbs/reject", summary: "Отклонить заявку на возврат" },
    { method: "POST", path: "/v2/returns/rfbs/compensate", summary: "Вернуть часть стоимости товара" },
    { method: "POST", path: "/v2/returns/rfbs/verify", summary: "Одобрить заявку на возврат" },
    { method: "POST", path: "/v2/returns/rfbs/receive-return", summary: "Подтвердить получение товара на проверку" },
    { method: "POST", path: "/v2/returns/rfbs/return-money", summary: "Вернуть деньги покупателю" },
    { method: "POST", path: "/v1/returns/rfbs/action/set", summary: "Передать доступные действия для rFBS возвратов" },
  ]},
  { name: "Receipt", endpoints: [
    { method: "POST", path: "/v1/receipts/get", summary: "Получить чек в формате PDF" },
    { method: "POST", path: "/v1/receipts/seller/list", summary: "Список чеков продавца" },
    { method: "POST", path: "/v1/receipts/upload", summary: "Загрузить чек" },
  ]},
  { name: "ReportAPI", endpoints: [
    { method: "POST", path: "/v1/report/info", summary: "Информация об отчёте" },
    { method: "POST", path: "/v1/report/list", summary: "Список отчётов" },
    { method: "POST", path: "/v1/report/products/create", summary: "Отчёт по товарам" },
    { method: "POST", path: "/v2/report/returns/create", summary: "Отчёт о возвратах" },
    { method: "POST", path: "/v1/report/postings/create", summary: "Отчёт об отправлениях" },
    { method: "POST", path: "/v1/finance/cash-flow-statement/list", summary: "Финансовый отчёт" },
    { method: "POST", path: "/v1/report/discounted/create", summary: "Отчёт об уценённых товарах" },
    { method: "POST", path: "/v1/report/warehouse/stock", summary: "Отчёт об остатках на FBS-складе" },
    { method: "POST", path: "/v1/report/placement/by-products/create", summary: "Отчёт о стоимости размещения по товарам" },
    { method: "POST", path: "/v1/report/placement/by-supplies/create", summary: "Отчёт о стоимости размещения по поставкам" },
    { method: "POST", path: "/v1/report/marked-products-sales/create", summary: "Отчёт по продажам товаров с маркировкой" },
  ]},
  { name: "ReturnAPI", endpoints: [
    { method: "POST", path: "/v1/returns/company/fbs/info", summary: "Количество возвратов FBS" },
    { method: "POST", path: "/v1/return/giveout/is-enabled", summary: "Проверить возможность получения возвратных отгрузок" },
    { method: "POST", path: "/v1/return/giveout/list", summary: "Список возвратных отгрузок" },
    { method: "POST", path: "/v1/return/giveout/info", summary: "Информация о возвратной отгрузке" },
    { method: "POST", path: "/v1/return/giveout/barcode", summary: "Штрихкод для возвратных отгрузок" },
    { method: "POST", path: "/v1/return/giveout/get-pdf", summary: "Штрихкод для возвратной отгрузки в PDF" },
    { method: "POST", path: "/v1/return/giveout/get-png", summary: "Штрихкод для возвратной отгрузки в PNG" },
    { method: "POST", path: "/v1/return/giveout/barcode-reset", summary: "Сгенерировать новый штрихкод" },
  ]},
  { name: "ReturnsAPI", endpoints: [
    { method: "POST", path: "/v1/returns/list", summary: "Информация о возвратах FBO и FBS" },
  ]},
  { name: "ReviewAPI", endpoints: [
    { method: "POST", path: "/v1/review/comment/create", summary: "Оставить комментарий на отзыв" },
    { method: "POST", path: "/v1/review/comment/delete", summary: "Удалить комментарий на отзыв" },
    { method: "POST", path: "/v1/review/comment/list", summary: "Список комментариев на отзыв" },
    { method: "POST", path: "/v1/review/change-status", summary: "Изменить статус отзывов" },
    { method: "POST", path: "/v1/review/count", summary: "Количество отзывов по статусам" },
    { method: "POST", path: "/v1/review/info", summary: "Информация об отзыве" },
    { method: "POST", path: "/v1/review/list", summary: "Список отзывов" },
  ]},
  { name: "SellerActions", endpoints: [
    { method: "POST", path: "/v1/seller-actions/create/discount", summary: "Создать акцию «Скидка»" },
    { method: "POST", path: "/v1/seller-actions/create/discount-with-condition", summary: "Создать акцию «Скидка от суммы заказа»" },
    { method: "POST", path: "/v1/seller-actions/create/installment", summary: "Создать акцию «Беспроцентная рассрочка»" },
    { method: "POST", path: "/v1/seller-actions/create/multi-level-discount", summary: "Создать акцию «Многоуровневая скидка от суммы»" },
    { method: "POST", path: "/v1/seller-actions/create/ozon-card-discount", summary: "Создать акцию «Повышенная скидка с Ozon Картой»" },
    { method: "POST", path: "/v1/seller-actions/create/voucher", summary: "Создать акцию «Скидка по промокоду»" },
    { method: "POST", path: "/v1/seller-actions/update/discount", summary: "Обновить акцию «Скидка»" },
    { method: "POST", path: "/v1/seller-actions/update/discount-with-condition", summary: "Обновить акцию «Скидка от суммы заказа»" },
    { method: "POST", path: "/v1/seller-actions/update/installment", summary: "Обновить акцию «Беспроцентная рассрочка»" },
    { method: "POST", path: "/v1/seller-actions/update/multi-level-discount", summary: "Обновить акцию «Многоуровневая скидка от суммы»" },
    { method: "POST", path: "/v1/seller-actions/update/ozon-card-discount", summary: "Обновить акцию «Повышенная скидка с Ozon Картой»" },
    { method: "POST", path: "/v1/seller-actions/update/voucher", summary: "Обновить акцию «Скидка по промокоду»" },
    { method: "POST", path: "/v1/seller-actions/products/add", summary: "Добавить товары в акцию" },
    { method: "POST", path: "/v1/seller-actions/products/candidates", summary: "Доступные для акции товары" },
    { method: "POST", path: "/v1/seller-actions/products/delete", summary: "Удалить товары из акции" },
    { method: "POST", path: "/v1/seller-actions/products/list", summary: "Участвующие в акции товары" },
    { method: "POST", path: "/v1/seller-actions/archive", summary: "Перенести акцию в архив" },
    { method: "POST", path: "/v1/seller-actions/change-activity", summary: "Включить или выключить акцию" },
    { method: "POST", path: "/v1/seller-actions/list", summary: "Список акций" },
    { method: "POST", path: "/v1/seller-actions/voucher/get", summary: "Получить файл с промокодами в CSV" },
  ]},
  { name: "SellerInfo", endpoints: [
    { method: "POST", path: "/v1/seller/info", summary: "Информация о кабинете продавца" },
    { method: "POST", path: "/v1/seller/ozon-logistics/info", summary: "Информация о подключении Ozon Логистики" },
  ]},
  { name: "SellerRating", endpoints: [
    { method: "POST", path: "/v1/rating/summary", summary: "Текущие рейтинги продавца" },
    { method: "POST", path: "/v1/rating/history", summary: "Рейтинги продавца за период" },
    { method: "POST", path: "/v1/rating/index/fbs/info", summary: "Индекс ошибок FBS и rFBS" },
    { method: "POST", path: "/v1/rating/index/fbs/posting/list", summary: "Отправления, повлиявшие на индекс ошибок" },
  ]},
  { name: "SupplierAPI", endpoints: [
    { method: "POST", path: "/v2/invoice/create-or-update", summary: "Создать или изменить счёт-фактуру" },
    { method: "POST", path: "/v1/invoice/file/upload", summary: "Загрузка счёта-фактуры" },
    { method: "POST", path: "/v2/invoice/get", summary: "Информация о счёте-фактуре" },
    { method: "POST", path: "/v1/invoice/delete", summary: "Удалить ссылку на счёт-фактуру" },
  ]},
  { name: "WarehouseAPI", endpoints: [
    { method: "POST", path: "/v1/warehouse/list", summary: "Список складов" },
    { method: "POST", path: "/v1/delivery-method/list", summary: "Список методов доставки склада" },
    { method: "POST", path: "/v2/delivery-method/list", summary: "Список методов доставки realFBS-склада" },
    { method: "POST", path: "/v1/delivery-method/return/settings/get", summary: "Возвратные настройки rFBS и rFBS Express" },
    { method: "POST", path: "/v2/warehouse/list", summary: "Список складов (v2)" },
    { method: "POST", path: "/v1/warehouse/operation/status", summary: "Статус операции" },
    { method: "POST", path: "/v1/warehouse/archive", summary: "Перенести склад в архив" },
    { method: "POST", path: "/v1/warehouse/unarchive", summary: "Перенести склад из архива" },
    { method: "POST", path: "/v1/warehouse/invalid-products/get", summary: "Товары с ограничениями по доставке" },
    { method: "POST", path: "/v1/warehouse/warehouses-with-invalid-products", summary: "Склады с ограниченными для доставки товарами" },
  ]},
  { name: "rFBSWarehouseSetup", endpoints: [
    { method: "POST", path: "/v1/warehouse/erfbs/aggregator/create", summary: "Создать склад с доставкой «Партнёры Ozon»" },
    { method: "POST", path: "/v1/warehouse/erfbs/update", summary: "Обновить склад" },
    { method: "POST", path: "/v1/warehouse/erfbs/aggregator/delivery-method/update", summary: "Обновить метод «Партнёры Ozon»" },
    { method: "POST", path: "/v1/warehouse/erfbs/non-integrated/create", summary: "Создать склад «Вы или сторонняя служба»" },
    { method: "POST", path: "/v1/warehouse/erfbs/non-integrated/delivery-method/update", summary: "Обновить метод «Вы или сторонняя служба»" },
  ]},
]
