FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/index.html
COPY favicon.png /usr/share/nginx/html/favicon.png
COPY logo.png /usr/share/nginx/html/logo.png
COPY apple-touch-icon.png /usr/share/nginx/html/apple-touch-icon.png
EXPOSE 80
